### ISSUE TITLE
Is it possible to use Retry in NodeRed?

### ISSUE THREAD

**Issue by narfotic** [amitfin/retry#45]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/amitfin/retry/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I was wondering if it is possible to use Retry in NodeRed?

### Describe the solution you'd like

I would like to be able to use Retry in NodeRed.

### Describe alternatives you've considered

I have all my automations in NodeRed. I would have to migrate everything to HA to use your code.

### Additional context

No additional context.

**Comment by amitfin** [comment]
[Disclaimer: I'm not an expert (or even a user) of NodeRed.]

It seems that NodeRed supports [call service](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/tree/main/src/nodes/call-service).  
Can you elaborate on the scenario? What is not working when calling `retry.call` from NodeRed?

<img width="1166" alt="image" src="https://github.com/amitfin/retry/assets/19599059/47e98dad-96d2-4a2f-80c2-4db363da948b">

**Comment by NathanVanCleave** [comment]
For anyone else trying to figure this out, here is an example of how I'm using this in Node Red.

The service needs to be "action", not "call" (not sure why, but this works).
<img width="800" alt="Screenshot 2024-01-22 at 9 02 46 AM" src="https://github.com/amitfin/retry/assets/26234190/eeee219f-32c2-4fc3-97eb-b9bfcd888c31">
<img width="348" alt="Screenshot 2024-01-22 at 8 57 45 AM" src="https://github.com/amitfin/retry/assets/26234190/a2368a48-2f8e-4f09-b690-aecf453c2585">

Something I'm noticing, though, is that in Node Red the payload is not getting passed along. I'm guessing this has something to do with how the service call is getting wrapped. This example works with the normal tts.google_translate_say service call where `{{payload}}` is a string passed from the previous node, but when using retry.action (the screenshot below) it errors out.
![Image 1-22-24 at 9 01 AM](https://github.com/amitfin/retry/assets/26234190/fc746ecd-8fec-41b4-aa65-205e707a1b42)

@amitfin, since you're not a Node Red user I don't expect a resolution, just wanted to point it out.
